### ISSUE TITLE
ERROR:  RepeatExplorer2 not found!

### ISSUE THREAD

**Issue by inud3mon** [crimBubble/ECCsplorer#10]
Hi @crimBubble 

I have been trying to run ECCsplorer but every I have tried i get the same error telling me RepeatExplorer2 is not installed 

2022-09-09 12:42:57,003 - [setup_logging] INFO: Starting ECCsplorer pipeline with...
Output directory:          eccpipe
Prefix data set A:         TR
File 1 data set A (f1a):   Trimm_R1_paired.fastqsanger
File 2 data set A (f2a):   Trimm_R2_paired.fastqsanger
Prefix data set B:         CO
File 1 data set B (f1b):   ---
File 2 data set B (f2b):   ---
Reference genome sequence: reference.fasta
Custom BLAST+ database:    None
Taxon:                     met
Read trimming option:      None
Mapping window size:       100
Genome size:               ---
User read count:           not set, using max. available reads
Run mode:                  all
Image format:              png
Max threads used:          8
Logging to file:           Yes
2022-09-09 12:42:57,003 - [basic_checkups] INFO: Performing basic checkups.
2022-09-09 12:42:57,003 - [basic_checkups] ERROR: 
RepeatExplorer2 not found!

Please make sure RepeatExplorer2 is installed.
If you installed RepeatExplorer2 using conda, please activate the environment
before starting the ECCsplorer pipeline.
If not in PATH modify location: config > REPEATEXPLORER_PATH.

I have changed the file path in config.py and I have independently confirmed RepeatExplorer2 will run using a test data set

And for ls all 
total 188
-rwxrwxr-x  1 jenn jenn 31687 Sep  8 22:10 seqclust

Thanks,

Jenn

**Comment by crimBubble** [comment]
Hi @inud3mon 
sorry for the late reply, but I was unavailable due to vacation/illness.

Please check if inside the config.py file (in the lib folder) the path/file-location to your RepeatExplorer executable is set correctly. Open the file with any text-editor and set the variable REPEATEXPLORER_PATH to match the location of the seqclust file. It should look something like:

`REPEATEXPLORER_PATH = /home/user/.../RepeatExplorer/seqclust`

**Comment by inud3mon** [comment]
Hi @crimBubble

Thank for you for your reply. 

Yea I have modified the config.py file to include the correct location but it still is not finding repeat explorer. A colleague of mine tried as well and also could not independently get repeat explorer to run. The mapping module runs fine, Trimmomatic etc. 

I'm not sure what else to do.

Thank for your time
