### ISSUE TITLE
detect from bam file ?

### ISSUE THREAD

**Issue by njaupan** [crimBubble/ECCsplorer#2]
Hi,

I am trying to benchmark your tool with circle-map, circle_finder and etc on a dataset of large plant genome (17G).

However, in the innitial step of index reference genome, segemehl produced large index file on disk: ~ 200G after 12 hours. It later broken on a cluster with 96 CPUS and 496 GB memory, so the aligner did not work well for large genome.
I have noticed that ECCsplorer uses haarz to detect split read from bed file produced by segemehl, I have tested the bam produced from different aligner such as BWA but it could not compile because they won't produce the split bed file. 

Do you think it can be resloved so that ECCsplorer works on other bam?

Best,
panpan

**Comment by crimBubble** [comment]
Hi panpan,

thanks for your feedback.

Currently the ECCsplorer pipeline only works with the segemehl output. We found that the split read detection using segemehl/haarz is more accurate than using other aligners e.g. bwa-mem combined with circle-map's SR detection. Unfortunately, segemehl is very RAM intensive especially on large genomes. It is currently not planned to introduce a new stand-alone SR detection algorithm to the ECCsplorer pipeline. For now, the only option to analyze large genomes is to run them section by section.

**Comment by njaupan** [comment]
Segemehl failed int the alignment so run it section by section won't work either, but many thanks.

Best,
panpan

**Comment by crimBubble** [comment]
The alignment likely failed because of not enough available RAM (yes even with ~500 GB). So running it in smaller parts should help. I think the RAM usage of segemehl migth increase exponentional with genome size.

Best, 
Ludwig
