### ISSUE TITLE
lost my favorate eccDNA

### ISSUE THREAD

**Issue by njaupan** [crimBubble/ECCsplorer#3]
Hi,
I again tested it on the arabidopsis which genome size is 120Mb, which in this mutant ONSEN are known to form eccDNA ( split read alignment for this element attached in the picture).
However, within 25 circular site produced by ECCsplorer, all are coorsponding to rDNA/MT/PLtd, and none is ONSEN.
which paramter that i can adjust?

![Screenshot from 2021-06-28 16-45-37](https://user-images.githubusercontent.com/8072119/123656517-4a35c600-d830-11eb-876b-26cdff95a3d4.png)

**Comment by crimBubble** [comment]
Hi,
it is really hard to tell from just the picture why it was not detected. The SR look fine in the picture. Maybe have a look into the files for the different eccDNA criteria (mapper_results > regions-all.bed, regions-DR.bed or regions-SR.bed) and see whether this region is present there. And also have a look into the cnfdc-ECC-regions.bed for the candidates with lower confidence (2 out of 3 matching criteria).
Best, Ludwig

**Comment by njaupan** [comment]
Hi, thanks for the quick response,
There is 3 sites from the regions-SR.bed, but no site from TR_lowconf-ECC-regions_SR-DR.bed.
Any idea?

**Comment by crimBubble** [comment]
Hi, this means there are no discordant mapping reads found which are one of the characteristics of eccDNA. Therefor the candidate is not considered as region with high confidence from the ECCsplorer pipeline. The split reads alone can also occur from solo-LTRs or other retrotransposon copies and may give false positive results in general. This candidate would need experimental verification.

**Comment by njaupan** [comment]
Hi,
Because it is experimental validated material, given the only heat stress to wildtype, therefore at least the master copy site of ONSEN should be detected.
I think the none discordant reads detected by ECCsplorer arise from the step after haarz.x detection, beacause I could see the discordant (down green) and split reads (upper green) here.
Correct me if I am wrong.
![Screenshot from 2021-06-29 09-35-20](https://user-images.githubusercontent.com/8072119/123756801-967b1780-d8bd-11eb-9237-fa6693353c41.png)

**Comment by crimBubble** [comment]
Hi, this should in deed be detected. The default minimal amount of split reads per region is five. You can change this setting in the lib/config.py by editing HAARZ_QUAL = ‘--minsplit 5’.

**Comment by crimBubble** [comment]
After personal communication, running the following command was able to detect ONSEN:
`python3 ECCsplorer.py RAW/Col7.R1.fastq.gz RAW/Col7.R2.fastq.gz -trm nex -d REF/act_TE.fas -ref REF/TAIR10_chr_1-5.fas -dsa onsen -dsb cntrl -cnt auto -out onsen3 -log -m map`
