### ISSUE TITLE
Something bugs

### ISSUE THREAD

**Issue by notchw** [crimBubble/ECCsplorer#4]
Hi author:
I am running ECCsplorer (2021-07-07 21:43:51,718), but the execution stuck until now (2021-07-13 10:08)
Stop at  "Calculating mean coverage of CO_map-all.MAPPING (ProcessID 76592; MultiID 51)"
![S__24829954](https://user-images.githubusercontent.com/84956744/125379265-ca2c6600-e3c2-11eb-99f5-48ecedf9ef0c.jpg)

There are something bugs after I checked the log.
I sent the log.txt to steve@bioinf.uni-leipzig.de
Can you help me to solve this  problem?

**Comment by crimBubble** [comment]
Hi,
please send the log to Ludwig.Mann@tu-dresden.de. The people from the Uni Leipzig developed the segemehl tool which is used here but they are not involved in the development ECCsplorer pipeline.
Thank you.

**Comment by crimBubble** [comment]
Please navigate to the ECCsplorer's config.py in the lib folder and change in line 192 the input option "--unmatched" to "--nomatchfilename" or download the updated config.py from github and exchange with the existing file. This should solve your issue.
