### ISSUE TITLE
Is ECCsplorer suitable for WGS?

### ISSUE THREAD

**Issue by xflicsu** [crimBubble/ECCsplorer#5]
Hi, I tried several eccDNA detector. 
Here, is ECCsplorer suitable for only one WGS data set (not amplified by phi29 polymerase)?
If yes, any suggestion for this situation?

**Comment by crimBubble** [comment]
Hi, the ECCsplorer pipeline is not suited for WGS data without amplification. The underlying approach is not capable to distinguish eccDNA from repetitive DNA without the experimental amplification procedure.
